# Generated by Django 4.2 on 2023-06-13 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
        ),
        migrations.CreateModel(
            name='jobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobgroup', models.CharField(max_length=10)),
                ('leaveDays', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('job_group', models.CharField(max_length=200, null=True)),
                ('leave_days', models.PositiveBigIntegerField(default=0, null=True)),
                ('tittle', models.CharField(choices=[('none', 'None'), ('vc', 'Vice Chancellor'), ('dvc', 'Deputy Vice Chancellor'), ('hod', 'Head Of Department'), ('hr', 'Human Resource')], default='none', max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='media/')),
                ('last_leave_year', models.PositiveIntegerField(default=0, null=True)),
                ('leave_days_previous_year', models.PositiveBigIntegerField(default=0, null=True)),
                ('leave_days_utilized_previous_year', models.PositiveBigIntegerField(default=0, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=200)),
                ('start_date', models.DateField(max_length=200)),
                ('end_date', models.DateField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('duties', models.CharField(max_length=200)),
                ('comment1', models.CharField(max_length=200, null=True)),
                ('leave_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('leave_status1', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
            ],
        ),
    ]
