# Generated by Django 4.2 on 2023-05-22 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('department', models.CharField(choices=[('ICT', 'ICT'), ('FINANCE', 'FINANCE'), ('ADMISSIONS', 'ADMISSIONS')], max_length=200, null=True)),
                ('section', models.CharField(choices=[('PLANNING', 'PLANNING'), ('SYSTEM', 'SYSTEM'), ('MAINTENANCE', 'MAINTENANCE')], max_length=200, null=True)),
                ('leave_days', models.PositiveIntegerField(default=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=200)),
                ('start_date', models.DateField(max_length=200)),
                ('end_date', models.DateField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('leave_status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('leave_status1', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.worker')),
            ],
        ),
    ]
