# Generated by Django 4.2 on 2023-06-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='last_leave_year',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='leave_days_previous_year',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='leave_days_utilized_previous_year',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
