# Generated by Django 4.2 on 2023-06-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_worker_last_leave_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='last_leave_year',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='leave_days_previous_year',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='leave_days_utilized_previous_year',
            field=models.PositiveBigIntegerField(default=0, null=True),
        ),
    ]
