# Generated by Django 4.2 on 2023-05-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_job_group_jobgroup_jobgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroup',
            name='leaveDays',
            field=models.CharField(max_length=100),
        ),
    ]
