# Generated by Django 4.2 on 2023-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_worker_department_alter_worker_job_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='media/'),
        ),
    ]
