# Generated by Django 4.2 on 2023-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jobgroup_leavedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobgroup',
            name='leaveDays',
            field=models.PositiveBigIntegerField(),
        ),
    ]
