# Generated by Django 4.2 on 2023-05-25 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_worker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='reporting_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'tittle__ne': 'none'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.worker'),
        ),
    ]
